trigger:
  - main

pool:
  name: Default

steps:

  - script: npm install
    displayName: 'Install dependencies'

  - script: npm test
    displayName: 'Run automated tests'

  - script: DOCKER_BUILDKIT=0 docker build -t shyamerukulla/employee-leave-app:latest -f Dockerfile .
    displayName: 'Build Docker image'

  - script: docker login --username shyamerukulla --password $(dockerHubPassword)
    displayName: 'Login to Docker Hub'

  - script: docker push shyamerukulla/employee-leave-app:latest
    displayName: 'Push to Docker Hub'
